const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ejs=require('ejs');const root=path.resolve(__dirname,'..');const {fixtures}=require('../scripts/theme-fixtures.cjs');
const theme=require('../src/lib/theme');
test('rollout switch selects the existing editor and landing routes without changing defaults',()=>{const previous=process.env.CODEPLAT_THEME_V2;try{delete process.env.CODEPLAT_THEME_V2;assert.equal(theme.themeV2(),false);assert.match(theme.pagePath('index'),/index-legacy\.html$/);process.env.CODEPLAT_THEME_V2='1';assert.match(theme.pagePath('index'),/index\.html$/);assert.match(theme.pagePath('landing'),/landing\.html$/);}finally{if(previous===undefined)delete process.env.CODEPLAT_THEME_V2;else process.env.CODEPLAT_THEME_V2=previous;}});
for(const page of ['login','signup','profile','dashboard','whiteboard','404','error'])for(const themeV2 of [false,true])test(`${page} renders with theme ${themeV2?'enabled':'disabled'} and valid browser scripts`,async()=>{const html=await ejs.renderFile(path.join(root,'src/views',page+'.ejs'),fixtures({themeV2,error:page==='error'?{}:null,message:page==='error'?'Unable to load workspace':null}));assert.equal(html.includes('src="/theme/theme.js"'),themeV2);assert.equal(html.includes('/journey/assets/'),false);for(const script of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(script[1],{filename:page});});
test('admin and other-user profile render with all controls and permission distinctions',async()=>{const admin=await ejs.renderFile(path.join(root,'src/views/dashboard.ejs'),fixtures({admin:true}));assert.match(admin,/\/admin\/user\/preview-user\/role/);const profile=await ejs.renderFile(path.join(root,'src/views/profile.ejs'),fixtures({viewingOther:true}));assert.equal(profile.includes('id="deleteAccountBtn"'),false);assert.equal(profile.includes('id="profileForm"'),false);});
function runtime(fetchImpl=async()=>new Response('{}')){
 const attrs=new Map();const element={dataset:{},getAttribute:key=>attrs.get(key)??null,setAttribute:(key,value)=>attrs.set(key,value),removeAttribute:key=>attrs.delete(key)};
 const document={querySelector:()=>null,querySelectorAll:selector=>selector==='#saveButton'?[element]:[],createElement:()=>({dataset:{},setAttribute(){}})};
 const window={CodeplatTheme:{get:()=> 'dark'},fetch:fetchImpl,addEventListener(){}};const context={window,document,URL,location:{href:'http://localhost/editor',origin:'http://localhost'},setTimeout:()=>1,clearTimeout(){},console};vm.runInNewContext(fs.readFileSync(path.join(root,'public/theme/ui.js'),'utf8'),context);return {window,element};
}
test('JSON helper preserves ordinary API data and safely handles text rate limits',async()=>{const {window}=runtime();assert.equal((await window.CodeplatUI.readJson(new Response('{"filename":"hello.js"}'))).filename,'hello.js');const data=await window.CodeplatUI.readJson(new Response('<html>rate limited</html>',{status:429}));assert.match(data.error,/Too many requests/);assert.equal(data.error.includes('<html>'),false);});
test('unexpected success HTML and expired-session redirects cannot be mistaken for successful mutations',async()=>{const {window}=runtime();await assert.rejects(window.CodeplatUI.readJson(new Response('<html>login</html>')),/unexpected response/);await assert.rejects(window.CodeplatUI.readJson({redirected:true,url:'http://localhost/login?error=expired'}),/session has expired/);});
test('request observer preserves response identity, payload and overlapping busy states',async()=>{const waiting=[];const response=new Response('{"ok":true}');const requests=[];const {window,element}=runtime((input,options)=>{requests.push([input,options]);return new Promise(resolve=>waiting.push(resolve));});const options={method:'POST',body:'{"code":"unchanged"}'};const one=window.fetch('/api/code/save',options),two=window.fetch('/api/code/save',options);assert.equal(element.getAttribute('aria-busy'),'true');waiting[0](response);assert.equal(await one,response);assert.equal(element.getAttribute('aria-busy'),'true');waiting[1](response);await two;assert.equal(element.getAttribute('aria-busy'),null);assert.equal(requests[0][1],options);});
test('failed and aborted requests release busy state without changing the original rejection',async()=>{const error=new Error('network failed');const {window,element}=runtime(async()=>{throw error;});await assert.rejects(window.fetch('/api/code/save'),value=>value===error);assert.equal(element.getAttribute('aria-busy'),null);});
test('unrelated requests bypass API presentation handling',async()=>{const response=new Response('external');const {window,element}=runtime(async()=>response);assert.equal(await window.fetch('https://example.test/resource'),response);assert.equal(element.getAttribute('aria-busy'),null);});
test('theme preference works when storage is unavailable and rejects unknown values',()=>{const rootElement={dataset:{}};const window={dispatchEvent(){},addEventListener(){}};const context={window,document:{documentElement:rootElement,querySelectorAll:()=>[],addEventListener(){}},localStorage:{getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail;}}};vm.runInNewContext(fs.readFileSync(path.join(root,'public/theme/theme.js'),'utf8'),context);assert.equal(window.CodeplatTheme.get(),'dark');window.CodeplatTheme.toggle();assert.equal(rootElement.dataset.codeplatTheme,'light');window.CodeplatTheme.set('invalid');assert.equal(rootElement.dataset.codeplatTheme,'dark');});
test('landing uses isolated assets and legacy HTML remains available',()=>{const landing=fs.readFileSync(path.join(root,'public/landing.html'),'utf8');assert.match(landing,/\/journey\/assets\//);const editor=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.equal(editor.includes('/journey/'),false);assert.match(editor,/id="editor"/);assert.match(fs.readFileSync(path.join(root,'public/index-legacy.html'),'utf8'),/id="editor"/);});
test('aborted API requests preserve AbortError and release busy state',async()=>{const error=new DOMException('Cancelled','AbortError');const {window,element}=runtime(async()=>{throw error;});await assert.rejects(window.fetch('/api/code/load'),value=>value===error);assert.equal(element.getAttribute('aria-busy'),null);});
test('existing root redirects and editor auth gate survive both presentations',async()=>{
 const express=require('express');const router=require('../src/routes');const previous=process.env.CODEPLAT_THEME_V2;
 const app=express();app.use((req,res,next)=>{req.session={};req.isAuthenticated=()=>req.headers['x-test-user']==='yes';next();});app.use(router);
 const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const url=`http://127.0.0.1:${server.address().port}`;
 try{for(const enabled of ['0','1']){process.env.CODEPLAT_THEME_V2=enabled;const root=await fetch(url+'/',{headers:{'x-test-user':'yes'},redirect:'manual'});assert.equal(root.status,302);assert.equal(root.headers.get('location'),'/editor');const guest=await fetch(url+'/editor',{redirect:'manual'});assert.equal(guest.status,302);assert.match(guest.headers.get('location'),/^\/login\?error=auth_required/);const editor=await fetch(url+'/editor',{headers:{'x-test-user':'yes'}});assert.equal(editor.status,200);assert.equal((await editor.text()).includes('/theme/theme.js'),enabled==='1');const landing=await fetch(url+'/landing');assert.equal(landing.status,200);assert.equal((await landing.text()).includes('/journey/assets/'),enabled==='1');}}
 finally{await new Promise(resolve=>server.close(resolve));if(previous===undefined)delete process.env.CODEPLAT_THEME_V2;else process.env.CODEPLAT_THEME_V2=previous;}
});
